name: "Sync Test Repo"

on:
  push:
    branches: [ "main" ]
    
jobs:
  sync:
      runs-on: ubantu-latest
      
      steps: 
        - uses: actions/checkout@v2
        
        - name: Sync and merge test repo
          uses: dabreadman/sync-upstream-repo@v1.3.0
          with:
            upstream_repo: https://github.com/go-trav/go-trav
            upstream_branch: main
            downstream_branch: main
            token: ${{ secrets.GITHUB_TOKEN }}
