name: "Sync Test"

on:
  push:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
     - name: Sync-Fork-action
       uses: XueMoMo/Sync-Fork-action@v1.0.6
       with:
          # Token for accessing the remote repo with authentication
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Upstream repository, e.g. => aormsby/Fork-Sync-With-Upstream-action
          upstream_repository: https://github.com/go-trav/go-trav/
          # Branch to sync from, e.g. => main, master, dev
          upstream_branch: main
          # Branch to push to, e.g. => main, master, prod
          target_branch: main
